# Generated by Django 5.1.4 on 2025-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slotifyBE", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
