# Generated by Django 4.2.20 on 2025-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='created_at',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='available_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='total_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
