# Generated by Django 5.2.1 on 2025-06-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0002_remove_parkinglot_created_at_parkinglot_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
