# Generated by Django 5.2.1 on 2025-06-21 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0003_parkinglot_password_parkinglot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='role',
            field=models.CharField(default='Owner', max_length=50),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
