# Generated by Django 5.2.1 on 2025-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0004_ownerprofile_created_at_ownerprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
