# Generated by Django 5.2.1 on 2025-06-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0005_ownerprofile_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLotCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('entry_x', models.FloatField()),
                ('entry_y', models.FloatField()),
                ('is_regular', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=False)),
                ('is_reservation', models.BooleanField(default=False)),
                ('lotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='slotifyBE.parkinglot')),
            ],
        ),
    ]
