# Generated by Django 5.2.1 on 2025-06-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0006_parkinglotcoordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglotcoordinate',
            name='is_Entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglotcoordinate',
            name='label',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
