# Generated by Django 5.2.1 on 2025-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0007_parkinglotcoordinate_is_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglotcoordinate',
            name='slot_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
