# Generated by Django 5.2.1 on 2025-06-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0008_parkinglotcoordinate_slot_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglotcoordinate',
            name='zone',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
