# Generated by Django 4.2.20 on 2025-07-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0011_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='verification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
