# Generated by Django 4.2.20 on 2025-07-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0012_ownerprofile_verification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='profileImage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
