# Generated by Django 4.2.20 on 2025-07-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0013_ownerprofile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
