# Generated by Django 4.2.20 on 2025-07-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotifyBE', '0014_alter_ownerprofile_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='profileImage',
        ),
    ]
