# Generated by Django 5.2.1 on 2025-06-18 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlateDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('camera_id', models.IntegerField()),
                ('detection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-detection_time'],
            },
        ),
    ]
