# Generated by Django 5.2.1 on 2025-06-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_parkingreservation_payment'),
        ('slotifyBE', '0010_alter_parkinglotcoordinate_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreservation',
            name='assigned_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slotifyBE.parkinglotcoordinate'),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slotifyBE.parkinglot'),
        ),
    ]
