# Generated by Django 5.2.1 on 2025-07-17 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_parkingreservation_assigned_slot_and_more'),
        ('slotifyBE', '0011_contactquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseplatedetection',
            options={},
        ),
        migrations.RemoveField(
            model_name='licenseplatedetection',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='licenseplatedetection',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='licenseplatedetection',
            name='detection_time',
        ),
        migrations.RemoveField(
            model_name='licenseplatedetection',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='licenseplatedetection',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='licenseplatedetection',
            name='user_confirmed',
        ),
        migrations.AddField(
            model_name='licenseplatedetection',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseplatedetection',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseplatedetection',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slotifyBE.parkinglot'),
        ),
    ]
