# Generated by Django 5.2.1 on 2025-07-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseplatedetection',
            name='detection_similarity_percentage',
            field=models.FloatField(blank=True, default=85, null=True),
        ),
    ]
