from django.urls import path
from . import views
from slotifyBE import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('userRegister/', views.userRegister, name='userRegister'),
    path('userSignIn/', views.userSignIn, name='userSignIn'),
    path('registerOwner/', views.register_owner, name='registerOwner'),
    path('registerParking/', views.parking_register_page, name='registerParkingPage'),
    path("getParkingLots/", views.get_parking_lots, name="get_parking_lots"),
    path("ownerDashboard/", views.get_owner_dashboard, name="get_owner_dashboard"),
    path('loginOwner/', views.login_owner, name='loginOwner'),
    path('options/', views.options_page, name='optionsPage'),
    path('logout/', views.logout_view, name='logout'),
    path('submitParking/', views.register_parking_lot, name='submit_parking'),
    path('nearbyParking/', views.nearby_parking, name='nearby_parking'),
    path('confirmParking/', views.confirm_parking, name='confirm_parking'),
    path('user-summary/', views.user_summary, name='user-summary'),
    path('getLandingPageStats/', views.get_landingPageStats, name="LandingPageStats"),
    path('about/', views.about, name="AboutPage"),
    path('features/', views.features, name="FeaturesPage"),
    path('contact/', views.contact, name="ContactPage"),
    path('submitContactQuery/', views.submit_contact_query, name='submit_contact_query'),
    path('verify-email/', views.otp_page, name='otp_page'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('reset-password/', views.render_password_final, name='reset_password_final'),
    path('update-password/', views.update_password, name='update_password'),
    path('forgot-password/', views.resubmitPassword, name='forgot_password'),
    path('verify-reset-otp/', views.verify_reset_otp, name='verify_reset_otp'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
    path('partials/overview/', views.overview_partial, name='overview_partial'),
    path('partials/revenue/', views.revenue_partial, name='revenue_partial'),
    path('partials/profile/', views.profile_partial, name='profile_partial'),
    path('revenue-data/', views.revenue_data, name='revenue-data'),
    path("occupancy-rate-data/", views.occupancy_rate_data, name="occupancy_rate_data"),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    path('revenue/', views.revenue_view, name='revenue'),
    path('update-logged-in-password/', views.update_logged_in_password, name='update_logged_in_password'),
]